### ISSUE TITLE
Rey 2do caso se parte

### ISSUE THREAD

**Issue by ViA8604** [ViA8604/Exam-Exercises-1#3]
Parece que hay que hacer una poda para el 2do caso del ejercicio Camino Seguro del Rey.

**Comment by Anthonycg2003** [comment]
![Captura de pantalla (10)](https://github.com/user-attachments/assets/6b4eab77-3173-429a-9b6d-793575ff9d5e)
El tema es que hay que ver si puedes llegar a la ultima casilla y no tienes  un muro de posiciones bloqueando para eso hice esta funcion. Pero ahora pensandolo bien puede darse otro caso en que esto no sirve

**Comment by Anthonycg2003** [comment]
![Captura de pantalla (125)_LI](https://github.com/user-attachments/assets/08ff9db0-eebb-4567-976e-a8fe5d00dd1a)
En ese caso se tendria una fila bloqueada y comiendose el peon que esta delante podria avanzar

**Comment by Anthonycg2003** [comment]
Creo que la solucion es que el rey solo vaya arriba, derecha y arriba derecha y cuando no encuentre salida retorne 0
![Captura de pantalla (126)_LI](https://github.com/user-attachments/assets/48d38f00-f1f5-4664-9701-3268255fd0bd)
